// =========================================================================
// Turquz Kariyer — içerik sözlüğü, 10 dil.
// CONTENT[key] = { tr, en, ru, kk, ky, uz, tk, de, th, fa }
// Eksik dil otomatik İngilizce'ye (sonra Türkçe'ye) düşer (LangContext.t).
// =========================================================================

export const CONTENT = {
  // ---- Marka dikey etiketi (logo yanı) ----
  'brand.vertical': { tr: 'Kariyer', en: 'Careers', ru: 'Карьера', kk: 'Мансап', ky: 'Карьера', uz: 'Karyera', tk: 'Karýera', de: 'Karriere', th: 'อาชีพ', fa: 'شغل' },

  // ---- Navigasyon ----
  'nav.offer':   { tr: 'Ne Sunuyoruz', en: 'What We Offer', ru: 'Что мы предлагаем', kk: 'Не ұсынамыз', ky: 'Эмне сунуштайбыз', uz: 'Nima taklif qilamiz', tk: 'Näme hödürleýäris', de: 'Was wir bieten', th: 'สิ่งที่เรามอบให้', fa: 'چه ارائه می‌دهیم' },
  'nav.partners':{ tr: 'Panel Girişi', en: 'Partner Login', ru: 'Вход для партнёров', kk: 'Серіктес кіруі', ky: 'Өнөктөш кирүү', uz: 'Hamkor kirishi', tk: 'Hyzmatdaş girişi', de: 'Partner-Login', th: 'เข้าสู่ระบบพาร์ทเนอร์', fa: 'ورود شرکا' },
  'nav.gallery': { tr: 'Sahadan', en: 'On the Ground', ru: 'Из жизни', kk: 'Іс жүзінде', ky: 'Талаадан', uz: 'Maydondan', tk: 'Meýdandan', de: 'Vor Ort', th: 'ภาคสนาม', fa: 'در میدان' },
  'nav.faq':     { tr: 'S.S.S.', en: 'FAQ', ru: 'Вопросы', kk: 'Сұрақтар', ky: 'Суроолор', uz: 'Savol-javob', tk: 'Soraglar', de: 'FAQ', th: 'คำถามที่พบบ่อย', fa: 'پرسش‌ها' },
  'nav.app':     { tr: 'İndir', en: 'Get the App', ru: 'Скачать', kk: 'Жүктеу', ky: 'Жүктөө', uz: 'Yuklab olish', tk: 'Ýükle', de: 'App holen', th: 'ดาวน์โหลด', fa: 'دریافت اپ' },
  'nav.main':    { tr: 'Turquz.com', en: 'Turquz.com', ru: 'Turquz.com', kk: 'Turquz.com', ky: 'Turquz.com', uz: 'Turquz.com', tk: 'Turquz.com', de: 'Turquz.com', th: 'Turquz.com', fa: 'Turquz.com' },

  // ---- HERO ----
  'hero.kicker': { tr: 'Turquz Kariyer', en: 'Turquz Careers', ru: 'Turquz Карьера', kk: 'Turquz Мансап', ky: 'Turquz Карьера', uz: 'Turquz Karyera', tk: 'Turquz Karýera', de: 'Turquz Karriere', th: 'Turquz อาชีพ', fa: 'مسیر شغلی Turquz' },
  'hero.title':  { tr: 'İnsanları, hak ettikleri', en: 'We connect people with the', ru: 'Мы соединяем людей с', kk: 'Адамдарды лайық', ky: 'Адамдарды татыктуу', uz: 'Insonlarni munosib', tk: 'Adamlary mynasyp', de: 'Wir verbinden Menschen mit der', th: 'เราเชื่อมผู้คนเข้ากับ', fa: 'مردم را به' },
  'hero.accent': { tr: 'kariyerle buluşturuyoruz', en: 'careers they deserve', ru: 'карьерой, которую они заслуживают', kk: 'мансаппен табыстырамыз', ky: 'карьера менен бириктиребиз', uz: 'karyera bilan bog‘laymiz', tk: 'karýera bilen birleşdirýäris', de: 'Karriere, die sie verdienen', th: 'อาชีพที่พวกเขาสมควรได้รับ', fa: 'شغلی که شایستهٔ آن‌اند می‌رسانیم' },
  'hero.sub':    { tr: 'Bir yanda hayallerinin peşindeki yetenekler, diğer yanda onlara güvenen işverenler. Turquz Kariyer ikisini; dil, mesafe ve sınır engeli olmadan güvenle buluşturur.', en: 'On one side, talent chasing a dream; on the other, employers ready to trust them. Turquz Careers brings the two together — beyond language, distance and borders.', ru: 'С одной стороны — таланты в поиске мечты, с другой — работодатели, готовые им довериться. Turquz Careers соединяет их, преодолевая язык, расстояние и границы.', kk: 'Бір жағында арманын қуған таланттар, екінші жағында оларға сенетін жұмыс берушілер. Turquz Kariyer екеуін тіл, қашықтық пен шекара кедергісінсіз сенімді түрде табыстырады.', ky: 'Бир жагында кыялын кууган таланттар, экинчи жагында аларга ишенген иш берүүчүлөр. Turquz Kariyer экөөнү тил, аралык жана чек ара тоскоолдугусуз ишенимдүү бириктирет.', uz: 'Bir tomonda orzusi ortidan ketayotgan iste’dodlar, boshqa tomonda ularga ishonadigan ish beruvchilar. Turquz Karyera ikkalasini til, masofa va chegara to‘sig‘isiz ishonch bilan bog‘laydi.', tk: 'Bir tarapda arzuwynyň yzyndan ýören zehinler, beýleki tarapda olara ynanýan iş berijiler. Turquz Karýera ikisini dil, aralyk we serhet päsgelçiligi bolmazdan ynamly birleşdirýär.', de: 'Auf der einen Seite Talente, die einem Traum folgen; auf der anderen Arbeitgeber, die ihnen vertrauen. Turquz Karriere bringt beide zusammen — über Sprache, Distanz und Grenzen hinweg.', th: 'ด้านหนึ่งคือคนเก่งที่ไล่ตามความฝัน อีกด้านคือนายจ้างที่พร้อมไว้วางใจ Turquz อาชีพ เชื่อมทั้งสองเข้าด้วยกัน — ข้ามภาษา ระยะทาง และพรมแดน', fa: 'در یک سو استعدادهایی که در پی رؤیای خود هستند و در سوی دیگر کارفرمایانی که به آنان اعتماد دارند. Turquz مسیر شغلی این دو را — فراتر از زبان، فاصله و مرز — به هم می‌رساند.' },
  'hero.cta1':   { tr: 'Uygulamayı İndir', en: 'Get the App', ru: 'Скачать приложение', kk: 'Қосымшаны жүктеу', ky: 'Колдонмону жүктөө', uz: 'Ilovani yuklab olish', tk: 'Programmany ýükle', de: 'App holen', th: 'ดาวน์โหลดแอป', fa: 'دریافت اپلیکیشن' },
  'hero.cta2':   { tr: 'Keşfet', en: 'Explore', ru: 'Узнать больше', kk: 'Білу', ky: 'Изилдөө', uz: 'Ko‘rib chiqish', tk: 'Öwren', de: 'Entdecken', th: 'สำรวจ', fa: 'کاوش' },

  // ---- INTRO (süslü) ----
  'intro.kicker': { tr: 'Bir Köprü, İki Hayat', en: 'One Bridge, Two Lives', ru: 'Один мост, две жизни', kk: 'Бір көпір, екі өмір', ky: 'Бир көпүрө, эки жашоо', uz: 'Bitta ko‘prik, ikki hayot', tk: 'Bir köpri, iki durmuş', de: 'Eine Brücke, zwei Leben', th: 'หนึ่งสะพาน สองชีวิต', fa: 'یک پل، دو زندگی' },
  'intro.title':  { tr: 'Kariyer, sadece bir iş değil; bir geleceğin başlangıcıdır', en: 'A career is not just a job — it’s the start of a future', ru: 'Карьера — это не просто работа, это начало будущего', kk: 'Мансап — жай жұмыс емес, болашақтың басталуы', ky: 'Карьера — жөн гана жумуш эмес, келечектин башталышы', uz: 'Karyera — shunchaki ish emas, kelajak boshlanishi', tk: 'Karýera — diňe iş däl, geljegiň başlangyjy', de: 'Eine Karriere ist nicht nur ein Job — sie ist der Beginn einer Zukunft', th: 'อาชีพไม่ใช่แค่งาน — แต่คือจุดเริ่มต้นของอนาคต', fa: 'مسیر شغلی فقط یک کار نیست؛ آغاز یک آینده است' },
  'intro.text':   { tr: 'Turquz Kariyer, otelcilik ve turizmde başlayan bir yolculuğun adıdır. Yetenekli adayları, kendilerine değer veren güvenilir işverenlerle buluşturuyoruz. Her profilin ardında bir hayal, her işin ardında bir fırsat olduğunu asla unutmadan.', en: 'Turquz Careers is a journey that began in hospitality and tourism. We connect talented candidates with trusted employers who value them — never forgetting that behind every profile is a dream, and behind every job an opportunity.', ru: 'Turquz Careers — это путь, начавшийся в сфере гостеприимства и туризма. Мы соединяем талантливых кандидатов с надёжными работодателями, которые их ценят, помня: за каждым профилем — мечта, за каждой работой — возможность.', kk: 'Turquz Kariyer — қонақжайлылық пен туризмнен басталған сапар. Талантты үміткерлерді оларды бағалайтын сенімді жұмыс берушілермен табыстырамыз; әр профильдің артында арман, әр жұмыстың артында мүмкіндік бар екенін ұмытпай.', ky: 'Turquz Kariyer — мейманканачылык менен туризмден башталган сапар. Таланттуу талапкерлерди аларды баалаган ишенимдүү иш берүүчүлөр менен бириктиребиз; ар бир профилдин артында кыял, ар бир иштин артында мүмкүнчүлүк бар экенин унутпай.', uz: 'Turquz Karyera — mehmondo‘stlik va turizmdan boshlangan sayohat. Iste’dodli nomzodlarni ularni qadrlaydigan ishonchli ish beruvchilar bilan bog‘laymiz; har bir profil ortida orzu, har bir ish ortida imkoniyat borligini unutmay.', tk: 'Turquz Karýera — myhmansöýerlik we syýahatçylykdan başlanan ýol. Zehinli dalaşgärleri olary gymmat saýýan ynamdar iş berijiler bilen birleşdirýäris; her profiliň aňyrsynda arzuw, her işiň aňyrsynda mümkinçilik bardygyny unutman.', de: 'Turquz Karriere ist eine Reise, die im Gastgewerbe und Tourismus begann. Wir verbinden talentierte Kandidaten mit vertrauenswürdigen Arbeitgebern, die sie schätzen — und vergessen nie, dass hinter jedem Profil ein Traum und hinter jeder Stelle eine Chance steht.', th: 'Turquz อาชีพ คือการเดินทางที่เริ่มต้นในธุรกิจโรงแรมและการท่องเที่ยว เราเชื่อมผู้สมัครที่มีความสามารถกับนายจ้างที่เชื่อถือได้และเห็นคุณค่าของพวกเขา โดยไม่ลืมว่าเบื้องหลังทุกโปรไฟล์คือความฝัน และเบื้องหลังทุกงานคือโอกาส', fa: 'Turquz مسیر شغلی سفری است که از مهمان‌نوازی و گردشگری آغاز شد. ما نامزدهای بااستعداد را به کارفرمایان مورد اعتمادی که قدرشان را می‌دانند می‌رسانیم — بی‌آنکه فراموش کنیم پشت هر پروفایل یک رؤیا و پشت هر شغل یک فرصت است.' },

  // ---- OFFER (aday + işveren) ----
  'offer.kicker': { tr: 'Ne Sunuyoruz', en: 'What We Offer', ru: 'Что мы предлагаем', kk: 'Не ұсынамыз', ky: 'Эмне сунуштайбыз', uz: 'Nima taklif qilamiz', tk: 'Näme hödürleýäris', de: 'Was wir bieten', th: 'สิ่งที่เรามอบให้', fa: 'چه ارائه می‌دهیم' },
  'offer.title':  { tr: 'İki taraf için de tek, akıcı bir deneyim', en: 'One seamless experience for both sides', ru: 'Единый удобный опыт для обеих сторон', kk: 'Екі тарап үшін де бір тұтас тәжірибе', ky: 'Эки тарап үчүн бир бүтүн тажрыйба', uz: 'Ikkala taraf uchun yagona uzluksiz tajriba', tk: 'Iki tarap üçin bir bitewi tejribe', de: 'Ein nahtloses Erlebnis für beide Seiten', th: 'ประสบการณ์ที่ราบรื่นสำหรับทั้งสองฝ่าย', fa: 'یک تجربهٔ یکپارچه برای هر دو سو' },
  'offer.lead':   { tr: 'Adaylar yeni bir hayat kurar, işverenler doğru yeteneğe ulaşır — hepsi tek bir platformda.', en: 'Candidates build a new life, employers reach the right talent — all on one platform.', ru: 'Кандидаты строят новую жизнь, работодатели находят нужных людей — всё на одной платформе.', kk: 'Үміткерлер жаңа өмір құрады, жұмыс берушілер дұрыс талантқа жетеді — бәрі бір платформада.', ky: 'Талапкерлер жаңы жашоо курат, иш берүүчүлөр туура талантка жетет — баары бир платформада.', uz: 'Nomzodlar yangi hayot quradi, ish beruvchilar to‘g‘ri iste’dodga yetadi — barchasi bitta platformada.', tk: 'Dalaşgärler täze durmuş gurýar, iş berijiler dogry zehine ýetýär — ählisi bir platformada.', de: 'Kandidaten bauen ein neues Leben auf, Arbeitgeber finden das richtige Talent — alles auf einer Plattform.', th: 'ผู้สมัครสร้างชีวิตใหม่ นายจ้างเข้าถึงคนที่ใช่ — ทั้งหมดบนแพลตฟอร์มเดียว', fa: 'نامزدها زندگی تازه‌ای می‌سازند و کارفرمایان به استعداد مناسب می‌رسند — همه در یک پلتفرم.' },

  'offer.cand.title': { tr: 'Adaylar için', en: 'For Candidates', ru: 'Для кандидатов', kk: 'Үміткерлерге', ky: 'Талапкерлерге', uz: 'Nomzodlar uchun', tk: 'Dalaşgärler üçin', de: 'Für Kandidaten', th: 'สำหรับผู้สมัคร', fa: 'برای نامزدها' },
  'offer.cand.li1': { tr: 'Kendi dilinizde, ücretsiz ve dakikalar içinde profesyonel CV', en: 'A professional CV in your language — free, in minutes', ru: 'Профессиональное резюме на вашем языке — бесплатно, за минуты', kk: 'Өз тіліңізде, тегін, бірнеше минутта кәсіби түйіндеме', ky: 'Өз тилиңизде, акысыз, бир нече мүнөттө кесипкөй CV', uz: 'O‘z tilingizda, bepul, bir necha daqiqada professional rezyume', tk: 'Öz diliňizde, mugt, birnäçe minutda hünärli CV', de: 'Ein professioneller Lebenslauf in Ihrer Sprache — kostenlos, in Minuten', th: 'เรซูเม่มืออาชีพในภาษาของคุณ — ฟรี ภายในไม่กี่นาที', fa: 'رزومهٔ حرفه‌ای به زبان شما — رایگان، در چند دقیقه' },
  'offer.cand.li2': { tr: 'Canlı çevirili görüntülü mülakat — dil engeli yok', en: 'Live-translated video interviews — no language barrier', ru: 'Видеоинтервью с живым переводом — без языкового барьера', kk: 'Аударма қосылған бейне сұхбат — тіл кедергісі жоқ', ky: 'Котормосу менен видео маек — тил тоскоолдугу жок', uz: 'Jonli tarjimali video suhbat — til to‘sig‘i yo‘q', tk: 'Terjimeli wideo söhbet — dil päsgelçiligi ýok', de: 'Live übersetzte Videointerviews — keine Sprachbarriere', th: 'สัมภาษณ์วิดีโอแปลสด — ไม่มีอุปสรรคทางภาษา', fa: 'مصاحبهٔ ویدیویی با ترجمهٔ زنده — بدون مانع زبانی' },
  'offer.cand.li3': { tr: 'Sözleşmeden uçak biletine kadar süreci telefonunuzdan takip', en: 'Track everything from contract to flight ticket on your phone', ru: 'Отслеживайте всё — от договора до авиабилета — со смартфона', kk: 'Келісімнен ұшақ билетіне дейін бәрін телефоныңыздан қадағалаңыз', ky: 'Келишимден учак билетине чейин баарын телефонуңуздан көзөмөлдөңүз', uz: 'Shartnomadan aviachiptagacha hammasini telefoningizdan kuzating', tk: 'Şertnamadan uçar biletine çenli ählisini telefonyňyzdan yzarlaň', de: 'Verfolgen Sie alles — vom Vertrag bis zum Flugticket — vom Handy', th: 'ติดตามทุกอย่างตั้งแต่สัญญาจนถึงตั๋วเครื่องบินจากโทรศัพท์', fa: 'همه چیز را از قرارداد تا بلیت پرواز از گوشی دنبال کنید' },

  'offer.emp.title': { tr: 'İşverenler için', en: 'For Employers', ru: 'Для работодателей', kk: 'Жұмыс берушілерге', ky: 'Иш берүүчүлөргө', uz: 'Ish beruvchilar uchun', tk: 'Iş berijiler üçin', de: 'Für Arbeitgeber', th: 'สำหรับนายจ้าง', fa: 'برای کارفرمایان' },
  'offer.emp.li1': { tr: 'Doğrulanmış havuzda pozisyon, dil ve beceriye göre akıllı filtreler', en: 'Smart filters by role, language and skill in a verified pool', ru: 'Умные фильтры по должности, языку и навыкам в проверенном пуле', kk: 'Расталған қорда лауазым, тіл және дағды бойынша ақылды сүзгілер', ky: 'Текшерилген пулда кызмат, тил жана көндүм боюнча акылдуу чыпкалар', uz: 'Tasdiqlangan bazada lavozim, til va ko‘nikma bo‘yicha aqlli filtrlar', tk: 'Tassyklanan gorda wezipe, dil we başarnyk boýunça akylly süzgüçler', de: 'Intelligente Filter nach Rolle, Sprache und Fähigkeit in einem geprüften Pool', th: 'ตัวกรองอัจฉริยะตามตำแหน่ง ภาษา และทักษะในฐานข้อมูลที่ตรวจสอบแล้ว', fa: 'فیلترهای هوشمند بر اساس نقش، زبان و مهارت در پایگاهی تأییدشده' },
  'offer.emp.li2': { tr: 'Adayla kendi dilinizde, canlı çeviriyle görüşün', en: 'Interview candidates in your own language with live translation', ru: 'Проводите собеседования на своём языке с живым переводом', kk: 'Үміткермен өз тіліңізде, тікелей аудармамен сөйлесіңіз', ky: 'Талапкер менен өз тилиңизде, түз котормо менен сүйлөшүңүз', uz: 'Nomzod bilan o‘z tilingizda, jonli tarjima bilan suhbatlashing', tk: 'Dalaşgär bilen öz diliňizde, göni terjime bilen söhbetleşiň', de: 'Führen Sie Interviews in Ihrer Sprache mit Live-Übersetzung', th: 'สัมภาษณ์ผู้สมัครในภาษาของคุณด้วยการแปลสด', fa: 'با نامزد به زبان خودتان و با ترجمهٔ زنده مصاحبه کنید' },
  'offer.emp.li3': { tr: 'Sözleşme, vize ve uçuş dâhil tüm süreç tek panelde, güvenle', en: 'The whole process — contract, visa, flight — in one secure panel', ru: 'Весь процесс — договор, виза, перелёт — в одной защищённой панели', kk: 'Бүкіл процесс — келісім, виза, рейс — бір қауіпсіз панельде', ky: 'Бүт процесс — келишим, виза, рейс — бир коопсуз панелде', uz: 'Butun jarayon — shartnoma, viza, reys — bitta xavfsiz panelda', tk: 'Ähli proses — şertnama, wiza, reýs — bir howpsuz panelde', de: 'Der gesamte Prozess — Vertrag, Visum, Flug — in einem sicheren Panel', th: 'ทั้งกระบวนการ — สัญญา วีซ่า เที่ยวบิน — ในแผงเดียวที่ปลอดภัย', fa: 'کل فرایند — قرارداد، ویزا، پرواز — در یک پنل امن' },

  // ---- GALLERY ----
  'gal.kicker': { tr: 'Sahadan', en: 'On the Ground', ru: 'Из жизни', kk: 'Іс жүзінде', ky: 'Талаадан', uz: 'Maydondan', tk: 'Meýdandan', de: 'Vor Ort', th: 'ภาคสนาม', fa: 'در میدان' },
  'gal.title':  { tr: 'Yüz yüze, gerçek buluşmalar', en: 'Face to face, real encounters', ru: 'Лицом к лицу, настоящие встречи', kk: 'Бетпе-бет, нағыз кездесулер', ky: 'Бетме-бет, чыныгы жолугушуулар', uz: 'Yuzma-yuz, haqiqiy uchrashuvlar', tk: 'Ýüzbe-ýüz, hakyky duşuşyklar', de: 'Von Angesicht zu Angesicht, echte Begegnungen', th: 'พบกันต่อหน้า การพบปะที่แท้จริง', fa: 'رو در رو، دیدارهای واقعی' },
  'gal.lead':   { tr: 'Öğrenci ve aday buluşmalarımızdan kareler — işin insani yüzü.', en: 'Moments from our student and candidate meetings — the human side of the work.', ru: 'Кадры с наших встреч со студентами и кандидатами — человеческая сторона работы.', kk: 'Студенттер мен үміткерлермен кездесулерімізден сәттер — істің адами жағы.', ky: 'Студенттер жана талапкерлер менен жолугушууларыбыздан учурлар — иштин адамдык жагы.', uz: 'Talabalar va nomzodlar bilan uchrashuvlarimizdan lavhalar — ishning insoniy tomoni.', tk: 'Talyplar we dalaşgärler bilen duşuşyklarymyzdan pursatlar — işiň ynsan tarapy.', de: 'Momente von unseren Treffen mit Studierenden und Kandidaten — die menschliche Seite der Arbeit.', th: 'ภาพจากการพบปะนักศึกษาและผู้สมัครของเรา — ด้านความเป็นมนุษย์ของงาน', fa: 'لحظاتی از دیدارهای ما با دانشجویان و نامزدها — چهرهٔ انسانی کار.' },
  'gal.empty':  { tr: 'Fotoğraflar yakında.', en: 'Photos coming soon.', ru: 'Фото скоро.', kk: 'Фотосуреттер жақында.', ky: 'Сүрөттөр жакында.', uz: 'Suratlar tez orada.', tk: 'Suratlar tizden.', de: 'Fotos folgen in Kürze.', th: 'ภาพถ่ายเร็ว ๆ นี้', fa: 'عکس‌ها به‌زودی.' },

  // ---- FAQ ----
  'faq.kicker': { tr: 'S.S.S.', en: 'FAQ', ru: 'Частые вопросы', kk: 'Жиі сұрақтар', ky: 'Көп берилген суроолор', uz: 'Ko‘p so‘raladigan savollar', tk: 'Köp berilýän soraglar', de: 'Häufige Fragen', th: 'คำถามที่พบบ่อย', fa: 'پرسش‌های متداول' },
  'faq.title':  { tr: 'Aklınızdaki sorular', en: 'Questions on your mind', ru: 'Ваши вопросы', kk: 'Сұрақтарыңыз', ky: 'Сурооларыңыз', uz: 'Savollaringiz', tk: 'Soraglaryňyz', de: 'Ihre Fragen', th: 'คำถามที่คุณอาจสงสัย', fa: 'پرسش‌های شما' },
  'faq.q1': { tr: 'Turquz Kariyer adaylar için ücretsiz mi?', en: 'Is Turquz Careers free for candidates?', ru: 'Turquz Careers бесплатный для кандидатов?', kk: 'Turquz Kariyer үміткерлерге тегін бе?', ky: 'Turquz Kariyer талапкерлерге акысызбы?', uz: 'Turquz Karyera nomzodlar uchun bepulmi?', tk: 'Turquz Karýera dalaşgärler üçin mugtmy?', de: 'Ist Turquz Karriere für Kandidaten kostenlos?', th: 'Turquz อาชีพ ฟรีสำหรับผู้สมัครหรือไม่?', fa: 'آیا Turquz برای نامزدها رایگان است؟' },
  'faq.a1': { tr: 'Evet. Adaylar uygulamayı indirip CV oluşturmak ve havuza katılmak için hiçbir ücret ödemez.', en: 'Yes. Candidates pay nothing to download the app, build a CV and join the pool.', ru: 'Да. Кандидаты ничего не платят за приложение, создание резюме и вступление в пул.', kk: 'Иә. Үміткерлер қосымшаны жүктеп, түйіндеме жасап, қорға қосылу үшін ештеңе төлемейді.', ky: 'Ооба. Талапкерлер колдонмону жүктөп, CV түзүп, пулга кошулуу үчүн эч нерсе төлөбөйт.', uz: 'Ha. Nomzodlar ilovani yuklab olish, rezyume tuzish va bazaga qo‘shilish uchun hech narsa to‘lamaydi.', tk: 'Hawa. Dalaşgärler programmany ýükläp, CV döredip, gora goşulmak üçin hiç zat tölemeýär.', de: 'Ja. Kandidaten zahlen nichts, um die App zu laden, einen Lebenslauf zu erstellen und dem Pool beizutreten.', th: 'ใช่ ผู้สมัครไม่เสียค่าใช้จ่ายในการดาวน์โหลดแอป สร้างเรซูเม่ และเข้าร่วมฐานข้อมูล', fa: 'بله. نامزدها برای دریافت اپ، ساخت رزومه و پیوستن به پایگاه هیچ هزینه‌ای نمی‌پردازند.' },
  'faq.q2': { tr: 'Hangi sektörlerde fırsat var?', en: 'Which sectors have opportunities?', ru: 'В каких сферах есть вакансии?', kk: 'Қай салаларда мүмкіндік бар?', ky: 'Кайсы тармактарда мүмкүнчүлүк бар?', uz: 'Qaysi sohalarda imkoniyat bor?', tk: 'Haýsy pudaklarda mümkinçilik bar?', de: 'In welchen Branchen gibt es Chancen?', th: 'มีโอกาสในภาคส่วนใดบ้าง?', fa: 'در چه بخش‌هایی فرصت هست؟' },
  'faq.a2': { tr: 'Otelcilik ve turizmde başladık; resepsiyon, servis, animasyon ve daha fazlası. Ağımız sürekli genişliyor.', en: 'We started in hospitality and tourism — reception, service, animation and more. Our network keeps growing.', ru: 'Мы начали с гостеприимства и туризма — ресепшн, сервис, анимация и не только. Наша сеть постоянно растёт.', kk: 'Қонақжайлылық пен туризмнен бастадық — ресепшн, сервис, анимация және т.б. Желіміз үнемі кеңеюде.', ky: 'Мейманканачылык менен туризмден баштадык — ресепшн, сервис, анимация ж.б. Тармагыбыз тынымсыз кеңейүүдө.', uz: 'Mehmondo‘stlik va turizmdan boshladik — qabulxona, xizmat, animatsiya va boshqalar. Tarmog‘imiz doimo kengaymoqda.', tk: 'Myhmansöýerlik we syýahatçylykdan başladyk — resepşn, hyzmat, animasiýa we başgalar. Ulgamymyz hemişe giňelýär.', de: 'Wir haben im Gastgewerbe und Tourismus begonnen — Rezeption, Service, Animation und mehr. Unser Netzwerk wächst stetig.', th: 'เราเริ่มในธุรกิจโรงแรมและการท่องเที่ยว — ต้อนรับ บริการ แอนิเมชัน และอื่น ๆ เครือข่ายของเราเติบโตอย่างต่อเนื่อง', fa: 'کار را در مهمان‌نوازی و گردشگری آغاز کردیم — پذیرش، سرویس، انیمیشن و بیشتر. شبکهٔ ما پیوسته در حال گسترش است.' },
  'faq.q3': { tr: 'Nasıl başvururum?', en: 'How do I apply?', ru: 'Как подать заявку?', kk: 'Қалай өтінім беремін?', ky: 'Кантип арыз берем?', uz: 'Qanday ariza beraman?', tk: 'Nädip ýüz tutmaly?', de: 'Wie bewerbe ich mich?', th: 'สมัครอย่างไร?', fa: 'چگونه درخواست بدهم؟' },
  'faq.a3': { tr: 'Uygulamayı indirin, kendi dilinizde CV’nizi oluşturun ve havuza katılın. Gerisini işverenler ve sistem hallediyor.', en: 'Download the app, build your CV in your language and join the pool. Employers and the system handle the rest.', ru: 'Скачайте приложение, создайте резюме на своём языке и вступите в пул. Остальное берут на себя работодатели и система.', kk: 'Қосымшаны жүктеңіз, өз тіліңізде түйіндеме жасап, қорға қосылыңыз. Қалғанын жұмыс берушілер мен жүйе атқарады.', ky: 'Колдонмону жүктөңүз, өз тилиңизде CV түзүп, пулга кошулуңуз. Калганын иш берүүчүлөр жана система аткарат.', uz: 'Ilovani yuklab oling, o‘z tilingizda rezyume tuzing va bazaga qo‘shiling. Qolganini ish beruvchilar va tizim bajaradi.', tk: 'Programmany ýükläň, öz diliňizde CV dörediň we gora goşulyň. Galanyny iş berijiler we ulgam edýär.', de: 'Laden Sie die App, erstellen Sie Ihren Lebenslauf in Ihrer Sprache und treten Sie dem Pool bei. Den Rest übernehmen Arbeitgeber und System.', th: 'ดาวน์โหลดแอป สร้างเรซูเม่ในภาษาของคุณ และเข้าร่วมฐานข้อมูล ที่เหลือนายจ้างและระบบจัดการให้', fa: 'اپ را دریافت کنید، رزومه‌تان را به زبان خود بسازید و به پایگاه بپیوندید. بقیه را کارفرمایان و سیستم انجام می‌دهند.' },
  'faq.q4': { tr: 'İşveren veya acente olarak nasıl katılırım?', en: 'How do I join as an employer or agency?', ru: 'Как присоединиться как работодатель или агентство?', kk: 'Жұмыс беруші немесе агенттік ретінде қалай қосыламын?', ky: 'Иш берүүчү же агенттик катары кантип кошулам?', uz: 'Ish beruvchi yoki agentlik sifatida qanday qo‘shilaman?', tk: 'Iş beriji ýa-da agentlik hökmünde nädip goşulmaly?', de: 'Wie trete ich als Arbeitgeber oder Agentur bei?', th: 'จะเข้าร่วมในฐานะนายจ้างหรือตัวแทนได้อย่างไร?', fa: 'به‌عنوان کارفرما یا آژانس چگونه بپیوندم؟' },
  'faq.a4': { tr: 'Acente paneline buradan girebilir veya uygulamadan kayıt olabilirsiniz — aynı e-posta ve şifre her iki yerde de geçerlidir. Yardım için bizimle iletişime geçin.', en: 'Sign in to the agency panel here, or register in the app — the same email and password work in both places. Contact us if you need help.', ru: 'Войдите в панель агентства здесь или зарегистрируйтесь в приложении — один email и пароль работают везде. Свяжитесь с нами при необходимости.', kk: 'Агенттік панеліне осында кіріңіз немесе қосымшадан тіркеліңіз — бірдей email мен құпия сөз екі жерде де жұмыс істейді. Көмек керек болса бізбен байланысыңыз.', ky: 'Агенттик панелге бул жерден кириңиз же колдонмодон катталыңыз — бир эле email жана сырсөз эки жерде да иштейт. Жардам керек болсо биз менен байланышыңыз.', uz: 'Agentlik paneliga shu yerdan kiring yoki ilovadan ro‘yxatdan o‘ting — bir xil email va parol ikkala joyda ham ishlaydi. Yordam kerak bo‘lsa biz bilan bog‘laning.', tk: 'Agentlik paneline şu ýerden giriň ýa-da programma arkaly hasaba alyň — birmeňzeş e-poçta we parol iki ýerde hem işleýär. Kömek gerek bolsa biz bilen habarlaşyň.', de: 'Melden Sie sich hier im Agentur-Panel an oder registrieren Sie sich in der App — dieselbe E-Mail und dasselbe Passwort gelten überall. Kontaktieren Sie uns bei Bedarf.', th: 'เข้าสู่ระบบแผงเอเจนซีที่นี่ หรือสมัครในแอป — อีเมลและรหัสผ่านเดียวกันใช้ได้ทั้งสองที่ ติดต่อเราหากต้องการความช่วยเหลือ', fa: 'از اینجا وارد پنل آژانس شوید یا در اپ ثبت‌نام کنید — همان ایمیل و رمز در هر دو جا کار می‌کند. در صورت نیاز با ما تماس بگیرید.' },
  'faq.q5': { tr: 'Yabancı dil bilmem şart mı?', en: 'Do I need to speak a foreign language?', ru: 'Нужно ли знать иностранный язык?', kk: 'Шетел тілін білуім шарт па?', ky: 'Чет тилди билишим шартпы?', uz: 'Chet tilini bilishim shartmi?', tk: 'Daşary ýurt dilini bilmek hökmanmy?', de: 'Muss ich eine Fremdsprache sprechen?', th: 'ฉันจำเป็นต้องพูดภาษาต่างประเทศไหม?', fa: 'آیا باید زبان خارجی بدانم؟' },
  'faq.a5': { tr: 'Hayır. Uygulama 10 dilde çalışır ve mülakatlar gerçek zamanlı çevrilir; herkes kendi dilinde konuşur.', en: 'No. The app works in 10 languages and interviews are translated in real time — everyone speaks their own language.', ru: 'Нет. Приложение работает на 10 языках, а собеседования переводятся в реальном времени — каждый говорит на своём языке.', kk: 'Жоқ. Қосымша 10 тілде жұмыс істейді, сұхбаттар нақты уақытта аударылады — әркім өз тілінде сөйлейді.', ky: 'Жок. Колдонмо 10 тилде иштейт, маектер реалдуу убакытта которулат — ар ким өз тилинде сүйлөйт.', uz: 'Yo‘q. Ilova 10 tilda ishlaydi va suhbatlar real vaqtda tarjima qilinadi — har kim o‘z tilida gapiradi.', tk: 'Ýok. Programma 10 dilde işleýär, söhbetler hakyky wagtda terjime edilýär — her kim öz dilinde gepleýär.', de: 'Nein. Die App funktioniert in 10 Sprachen und Interviews werden in Echtzeit übersetzt — jeder spricht seine Sprache.', th: 'ไม่ แอปทำงาน 10 ภาษาและการสัมภาษณ์แปลแบบเรียลไทม์ — ทุกคนพูดภาษาของตน', fa: 'خیر. اپ به ۱۰ زبان کار می‌کند و مصاحبه‌ها هم‌زمان ترجمه می‌شوند — هرکس به زبان خود صحبت می‌کند.' },
  'faq.q6': { tr: 'Kişisel verilerim güvende mi?', en: 'Is my personal data safe?', ru: 'Мои данные в безопасности?', kk: 'Жеке деректерім қауіпсіз бе?', ky: 'Жеке маалыматтарым коопсузбу?', uz: 'Shaxsiy ma’lumotlarim xavfsizmi?', tk: 'Şahsy maglumatlarym howpsuzmy?', de: 'Sind meine Daten sicher?', th: 'ข้อมูลส่วนตัวของฉันปลอดภัยไหม?', fa: 'آیا داده‌های شخصی‌ام امن است؟' },
  'faq.a6': { tr: 'Evet. İletişim bilgileriniz maskelenir, yalnızca karşılıklı onayla paylaşılır; tüm süreç KVKK uyumludur.', en: 'Yes. Your contact details are masked and shared only with mutual consent; the whole process is privacy-compliant.', ru: 'Да. Ваши контакты скрыты и раскрываются только при обоюдном согласии; весь процесс соответствует требованиям приватности.', kk: 'Иә. Байланыс деректеріңіз маскаланады, тек өзара келісіммен ашылады; бүкіл процесс құпиялылық талаптарына сай.', ky: 'Ооба. Байланыш маалыматыңыз маскаланат, өз ара макулдук менен гана ачылат; бүт процесс купуялык талаптарына шайкеш.', uz: 'Ha. Aloqa ma’lumotlaringiz maskalanadi va faqat o‘zaro rozilik bilan ochiladi; butun jarayon maxfiylik talablariga mos.', tk: 'Hawa. Aragatnaşyk maglumatlaryňyz maskalanýar, diňe özara razylyk bilen açylýar; ähli proses gizlinlik talaplaryna laýyk.', de: 'Ja. Ihre Kontaktdaten werden maskiert und nur mit beiderseitiger Zustimmung geteilt; der gesamte Prozess ist datenschutzkonform.', th: 'ใช่ ข้อมูลติดต่อของคุณถูกปกปิดและแชร์เมื่อได้รับความยินยอมร่วมกันเท่านั้น ทั้งกระบวนการเป็นไปตามข้อกำหนดความเป็นส่วนตัว', fa: 'بله. اطلاعات تماس شما پوشانده می‌شود و تنها با رضایت دوطرفه به اشتراک گذاشته می‌شود؛ کل فرایند با حریم خصوصی سازگار است.' },

  // ---- PARTNERS (acente / otel web girişi) ----
  'partners.kicker': { tr: 'İş ortakları', en: 'Partners', ru: 'Партнёры', kk: 'Серіктестер', ky: 'Өнөктөштөр', uz: 'Hamkorlar', tk: 'Hyzmatdaşlar', de: 'Partner', th: 'พาร์ทเนอร์', fa: 'شرکا' },
  'partners.title':  { tr: 'Bilgisayardan panelinize girin', en: 'Open your panel on the desktop', ru: 'Откройте панель на компьютере', kk: 'Компьютерден панеліңізге кіріңіз', ky: 'Компьютерден панелиңизге кириңиз', uz: 'Kompyuterdan panellingizga kiring', tk: 'Kompýuteriňizden paneliňize giriň', de: 'Öffnen Sie Ihr Panel am Desktop', th: 'เปิดแผงของคุณบนคอมพิวเตอร์', fa: 'پنل خود را روی رایانه باز کنید' },
  'partners.lead':   { tr: 'Acente ve otel ekipleri PC üzerinden süreçleri yönetir. İsterseniz uygulamadan da aynı hesapla devam edebilirsiniz.', en: 'Agency and hotel teams manage workflows on PC. You can also continue in the app with the same account.', ru: 'Команды агентств и отелей ведут процессы на ПК. Тот же аккаунт работает и в приложении.', kk: 'Агенттік пен қонақ үй командалары процестерді компьютерден басқарады. Сол есеппен қосымшада да жалғастыра аласыз.', ky: 'Агенттик жана мейманкана командалары процесстерди компьютерден башкарат. Ошол эле аккаунт менен колдонмодо да уланта аласыз.', uz: 'Agentlik va mehmonxona jamoalari jarayonlarni kompyuterdan boshqaradi. Xohlasangiz bir xil hisob bilan ilovada ham davom etishingiz mumkin.', tk: 'Agentlik we myhmanhana toparlary prosesleri kompýuterden dolandyrýar. Isleňizde şol bir hasap bilen programmada hem dowam edip bilersiňiz.', de: 'Agentur- und Hotelteams steuern Abläufe am PC. Mit demselben Konto geht es auch in der App weiter.', th: 'ทีมเอเจนซีและโรงแรมจัดการงานบนพีซี คุณสามารถใช้บัญชีเดียวกันต่อในแอปได้', fa: 'تیم‌های آژانس و هتل فرایندها را روی رایانه مدیریت می‌کنند. با همان حساب می‌توانید در اپ هم ادامه دهید.' },
  'partners.agency.title': { tr: 'Acente Girişi', en: 'Agency Login', ru: 'Вход для агентства', kk: 'Агенттік кіруі', ky: 'Агенттик кирүү', uz: 'Agentlik kirishi', tk: 'Agentlik girişi', de: 'Agentur-Login', th: 'เข้าสู่ระบบเอเจนซี', fa: 'ورود آژانس' },
  'partners.agency.desc':  { tr: 'Aday havuzu, mülakat, sözleşme ve uçuş — tek web panelinde.', en: 'Candidate pool, interviews, contracts and flights — in one web panel.', ru: 'Пул кандидатов, собеседования, договоры и рейсы — в одной веб-панели.', kk: 'Үміткерлер қоры, сұхбат, келісім және рейс — бір веб-панельде.', ky: 'Талапкерлер пулу, маек, келишим жана рейс — бир веб-панелде.', uz: 'Nomzodlar bazasi, suhbat, shartnoma va reys — bitta veb-panelda.', tk: 'Dalaşgärler howuzy, söhbet, şertnama we reýs — bir web panelinde.', de: 'Bewerberpool, Interviews, Verträge und Flüge — in einem Web-Panel.', th: 'กลุ่มผู้สมัคร สัมภาษณ์ สัญญา และเที่ยวบิน — ในแผงเว็บเดียว', fa: 'استخر نامزدها، مصاحبه، قرارداد و پرواز — در یک پنل وب.' },
  'partners.agency.cta':   { tr: 'Acente Girişi', en: 'Agency Login', ru: 'Вход для агентства', kk: 'Агенттік кіруі', ky: 'Агенттик кирүү', uz: 'Agentlik kirishi', tk: 'Agentlik girişi', de: 'Agentur-Login', th: 'เข้าสู่ระบบเอเจนซี', fa: 'ورود آژانس' },
  'partners.hotel.title':  { tr: 'Otel Girişi', en: 'Hotel Login', ru: 'Вход для отеля', kk: 'Қонақ үй кіруі', ky: 'Мейманкана кирүү', uz: 'Mehmonxona kirishi', tk: 'Myhmanhana girişi', de: 'Hotel-Login', th: 'เข้าสู่ระบบโรงแรม', fa: 'ورود هتل' },
  'partners.hotel.desc':   { tr: 'Otel ekibiniz için masaüstü panel — aday ve süreç takibi.', en: 'A desktop panel for your hotel team — candidates and process tracking.', ru: 'Панель для команды отеля — кандидаты и контроль процессов.', kk: 'Қонақ үй командаңызға арналған үстел панелі — үміткерлер мен процесс қадағалау.', ky: 'Мейманкана командаңыз үчүн стол панели — талапкерлер жана процесс көзөмөлү.', uz: 'Mehmonxona jamoangiz uchun ish stoli paneli — nomzodlar va jarayon kuzatuvi.', tk: 'Myhmanhana toparyňyz üçin stol paneli — dalaşgärler we proses yzarlamasy.', de: 'Desktop-Panel für Ihr Hotelteam — Kandidaten und Prozessverfolgung.', th: 'แผงเดสก์ท็อปสำหรับทีมโรงแรม — ผู้สมัครและติดตามกระบวนการ', fa: 'پنل دسکتاپ برای تیم هتل شما — نامزدها و پیگیری فرایند.' },
  'partners.hotel.cta':    { tr: 'Otel Girişi', en: 'Hotel Login', ru: 'Вход для отеля', kk: 'Қонақ үй кіруі', ky: 'Мейманкана кирүү', uz: 'Mehmonxona kirishi', tk: 'Myhmanhana girişi', de: 'Hotel-Login', th: 'เข้าสู่ระบบโรงแรม', fa: 'ورود هتل' },
  'partners.hotel.ctaSoon':{ tr: 'Çok yakında', en: 'Coming very soon', ru: 'Очень скоро', kk: 'Жақында', ky: 'Жакында', uz: 'Juda tez orada', tk: 'Örän tizden', de: 'Sehr bald', th: 'เร็ว ๆ นี้', fa: 'به‌زودی' },
  'partners.sync': { tr: 'Aynı e-posta ve şifre hem uygulamada hem web panelinde geçerlidir. Nereden kayıt olursanız olun hesabınız senkron kalır.', en: 'The same email and password work in the app and the web panel. Wherever you sign up, your account stays in sync.', ru: 'Один email и пароль работают в приложении и веб-панели. Где бы вы ни зарегистрировались — аккаунт синхронен.', kk: 'Бірдей email мен құпия сөз қосымшада да, веб-панельде де жұмыс істейді. Қайда тіркелсеңіз де есебіңіз синхронды.', ky: 'Бир эле email жана сырсөз колдонмодо да, веб-панелде да иштейт. Кайда катталсаңыз да аккаунтуңуз синхрондуу.', uz: 'Bir xil email va parol ham ilovada, ham veb-panelda ishlaydi. Qayerda ro‘yxatdan o‘tsangiz ham hisobingiz sinxron qoladi.', tk: 'Birmeňzeş e-poçta we parol hem programmada, hem web panelinde işleýär. Nireden hasaba alynsaňyz hasabyňyz sinhron galýar.', de: 'Dieselbe E-Mail und dasselbe Passwort gelten in App und Web-Panel. Wo Sie sich anmelden — Ihr Konto bleibt synchron.', th: 'อีเมลและรหัสผ่านเดียวกันใช้ได้ทั้งในแอปและแผงเว็บ ไม่ว่าจะสมัครที่ไหน บัญชีของคุณจะซิงค์กัน', fa: 'همان ایمیل و رمز در اپ و پنل وب کار می‌کند. هرجا ثبت‌نام کنید، حسابتان همگام می‌ماند.' },

  // ---- APP CTA ----
  'app.kicker': { tr: 'Hemen Başla', en: 'Start Now', ru: 'Начните сейчас', kk: 'Қазір баста', ky: 'Азыр башта', uz: 'Hozir boshlang', tk: 'Häzir başla', de: 'Jetzt starten', th: 'เริ่มเลย', fa: 'همین حالا شروع کنید' },
  'app.title':  { tr: 'Geleceğin cebinde başlasın', en: 'Let your future begin in your pocket', ru: 'Пусть будущее начнётся в вашем кармане', kk: 'Болашақ қалтаңыздан басталсын', ky: 'Келечек чөнтөгүңүздөн башталсын', uz: 'Kelajak cho‘ntagingizdan boshlansin', tk: 'Geljek jübüňizden başlasyn', de: 'Lass deine Zukunft in deiner Tasche beginnen', th: 'ให้อนาคตของคุณเริ่มต้นในกระเป๋า', fa: 'بگذارید آینده‌تان در جیب شما آغاز شود' },
  'app.text':   { tr: 'Turquz uygulamasını indir, kendi dilinde CV’ni oluştur ve doğru fırsatla buluş.', en: 'Download the Turquz app, build your CV in your language and meet the right opportunity.', ru: 'Скачайте приложение Turquz, создайте резюме на своём языке и найдите подходящую возможность.', kk: 'Turquz қосымшасын жүктеп, өз тіліңде түйіндеме жаса және дұрыс мүмкіндікпен табыс.', ky: 'Turquz колдонмосун жүктөп, өз тилиңде CV түзүп, туура мүмкүнчүлүк менен таныш.', uz: 'Turquz ilovasini yuklab oling, o‘z tilingizda rezyume tuzing va to‘g‘ri imkoniyatga ega bo‘ling.', tk: 'Turquz programmasyny ýükläp, öz diliňde CV döret we dogry mümkinçilik bilen tanyş.', de: 'Lade die Turquz-App, erstelle deinen Lebenslauf in deiner Sprache und finde die richtige Chance.', th: 'ดาวน์โหลดแอป Turquz สร้างเรซูเม่ในภาษาของคุณ และพบโอกาสที่ใช่', fa: 'اپلیکیشن Turquz را دریافت کنید، رزومه‌تان را به زبان خود بسازید و فرصت مناسب را بیابید.' },
  'app.soon':   { tr: 'Yakında', en: 'Coming soon', ru: 'Скоро', kk: 'Жақында', ky: 'Жакында', uz: 'Tez orada', tk: 'Tizden', de: 'Demnächst', th: 'เร็ว ๆ นี้', fa: 'به‌زودی' },

  // ---- FOOTER ----
  'foot.tagline': { tr: 'İnsanları hak ettikleri kariyerle buluşturan çok dilli köprü.', en: 'The multilingual bridge connecting people with the careers they deserve.', ru: 'Многоязычный мост, соединяющий людей с карьерой, которую они заслуживают.', kk: 'Адамдарды лайық мансаппен табыстыратын көп тілді көпір.', ky: 'Адамдарды татыктуу карьера менен бириктирген көп тилдүү көпүрө.', uz: 'Insonlarni munosib karyera bilan bog‘lovchi ko‘p tilli ko‘prik.', tk: 'Adamlary mynasyp karýera bilen birleşdirýän köp dilli köpri.', de: 'Die mehrsprachige Brücke, die Menschen mit der Karriere verbindet, die sie verdienen.', th: 'สะพานหลายภาษาที่เชื่อมผู้คนกับอาชีพที่พวกเขาสมควรได้รับ', fa: 'پل چندزبانه‌ای که مردم را به شغلی که شایسته‌اند می‌رساند.' },
  'foot.contact': { tr: 'İletişim', en: 'Contact', ru: 'Контакты', kk: 'Байланыс', ky: 'Байланыш', uz: 'Aloqa', tk: 'Aragatnaşyk', de: 'Kontakt', th: 'ติดต่อ', fa: 'تماس' },
  'foot.rights':  { tr: 'Tüm hakları saklıdır.', en: 'All rights reserved.', ru: 'Все права защищены.', kk: 'Барлық құқықтар қорғалған.', ky: 'Бардык укуктар корголгон.', uz: 'Barcha huquqlar himoyalangan.', tk: 'Ähli hukuklar goralan.', de: 'Alle Rechte vorbehalten.', th: 'สงวนลิขสิทธิ์', fa: 'تمام حقوق محفوظ است.' },
  'foot.disclaimer': { tr: 'Turquz bir işe alım kurumu değil, teknoloji platformudur.', en: 'Turquz is a technology platform, not a recruitment agency.', ru: 'Turquz — технологическая платформа, а не кадровое агентство.', kk: 'Turquz — жалдау агенттігі емес, технологиялық платформа.', ky: 'Turquz — жалдоо агенттиги эмес, технологиялык платформа.', uz: 'Turquz — yollash agentligi emas, texnologik platforma.', tk: 'Turquz — işe alyş agentligi däl, tehnologiýa platformasy.', de: 'Turquz ist eine Technologieplattform, keine Personalvermittlung.', th: 'Turquz เป็นแพลตฟอร์มเทคโนโลยี ไม่ใช่บริษัทจัดหางาน', fa: 'Turquz یک پلتفرم فناوری است، نه آژانس کاریابی.' },
};
