// Aday paneli SSS — uygulama işleyişi ve süreç hakkında.
// Desteklenen tüm diller: tr, en, ru, kk, ky, uz, tk, de, th, fa.
// Eksik dilde: seçilen dil → en → tr.

const FAQ = [
  {
    id: 'what',
    q: {
      tr: 'Turquz nedir?',
      en: 'What is Turquz?',
      ru: 'Что такое Turquz?',
      kk: 'Turquz дегеніміз не?',
      ky: 'Turquz деген эмне?',
      uz: 'Turquz nima?',
      tk: 'Turquz näme?',
      de: 'Was ist Turquz?',
      th: 'Turquz คืออะไร?',
      fa: 'Turquz چیست؟',
    },
    a: {
      tr: 'Turquz, yurt dışından Türkiye’deki otel ve işletmelere çalışmak isteyen adayları acentelerle buluşturan bir kariyer platformudur. Profilinizi oluşturur, teklifleri görür ve süreci uygulamadan takip edersiniz.',
      en: 'Turquz is a careers platform that connects candidates who want to work in hotels and businesses in Turkey with agencies. You build your profile, receive offers, and follow the whole process in the app.',
      ru: 'Turquz — платформа, которая соединяет кандидатов, желающих работать в отелях и компаниях Турции, с агентствами. Вы создаёте профиль, получаете предложения и ведёте процесс в приложении.',
      kk: 'Turquz — Түркиядағы қонақүйлер мен кәсіпорындарда жұмыс істегісі келетін үміткерлерді агенттіктермен байланыстыратын мансап платформасы. Профиль жасайсыз, ұсыныстар аласыз және бүкіл үдерісті қолданбадан қадағалайсыз.',
      ky: 'Turquz — Түркиядагы мейманканаларда жана ишканаларда иштегиси келген талапкерлерди агенттиктер менен байланыштырган карьера платформасы. Профиль түзөсүз, сунуштар аласыз жана бүт процесс колдонмодо жүрет.',
      uz: 'Turquz — Turkiyadagi mehmonxona va korxonalarda ishlashni xohlaydigan nomzodlarni agentliklar bilan bog‘laydigan karyera platformasi. Profilingizni yaratasiz, takliflar olasiz va jarayonni ilovadan kuzatasiz.',
      tk: 'Turquz — Türkiýedäki myhmanhanalarda we kärhanalarda işlemegi isleýän dalaşgärleri agentlikler bilen baglanyşdyrýan karýera platformasy. Profil döredýärsiňiz, teklip alýarsyňyz we prosesi programmada yzarlaýarsyňyz.',
      de: 'Turquz verbindet Bewerber, die in Hotels und Betrieben in der Türkei arbeiten möchten, mit Agenturen. Sie erstellen Ihr Profil, erhalten Angebote und begleiten den Prozess in der App.',
      th: 'Turquz เป็นแพลตฟอร์มอาชีพที่เชื่อมผู้สมัครที่อยากทำงานในโรงแรมและธุรกิจในตุรกีกับเอเจนซี คุณสร้างโปรไฟล์ รับข้อเสนอ และติดตามกระบวนการทั้งหมดในแอป',
      fa: 'Turquz پلتفرم شغلی است که داوطلبان مایل به کار در هتل‌ها و کسب‌وکارهای ترکیه را به آژانس‌ها وصل می‌کند. پروفایل می‌سازید، پیشنهاد می‌گیرید و کل فرایند را در اپ دنبال می‌کنید.',
    },
  },
  {
    id: 'flow',
    q: {
      tr: 'Süreç nasıl ilerler?',
      en: 'How does the process work?',
      ru: 'Как проходит процесс?',
      kk: 'Үдеріс қалай жүреді?',
      ky: 'Процесс кантип жүрөт?',
      uz: 'Jarayon qanday kechadi?',
      tk: 'Proses nähili dowam edýär?',
      de: 'Wie läuft der Prozess ab?',
      th: 'กระบวนการเป็นอย่างไร?',
      fa: 'فرایند چگونه پیش می‌رود؟',
    },
    a: {
      tr: '1) Profil ve CV’nizi tamamlayın.\n2) Acenteler sizi görür; mülakat veya doğrudan iş teklifi gelebilir.\n3) Teklifi kabul edince belge adımları açılır.\n4) Belge işlemleri tamamlanınca uçak biletiniz gönderilir ve yeni kariyerinize başlarsınız.',
      en: '1) Complete your profile and CV.\n2) Agencies see you; you may get an interview or a direct job offer.\n3) After you accept an offer, document steps unlock.\n4) When the documents are done, your flight ticket is sent and you start your new career.',
      ru: '1) Заполните профиль и резюме.\n2) Агентства видят вас; возможен собеседование или прямое предложение.\n3) После принятия предложения открываются документы.\n4) Когда документы готовы, вам отправят авиабилет — и вы начнёте новую карьеру.',
      kk: '1) Профиль мен CV-ді толтырыңыз.\n2) Агенттіктер сізді көреді; сұхбат немесе тікелей жұмыс ұсынысы келуі мүмкін.\n3) Ұсынысты қабылдаған соң құжат қадамдары ашылады.\n4) Құжаттар біткенде ұшақ билетіңіз жіберіледі — жаңа мансабыңыз басталады.',
      ky: '1) Профиль жана CV толтуруңуз.\n2) Агенттиктер сизди көрөт; маек же түз жумуш сунушу келиши мүмкүн.\n3) Сунушту кабылдагандан кийин документ кадамдары ачылат.\n4) Документтер бүткөндө учак билетиңиз жөнөтүлөт — жаңы карьераңыз башталат.',
      uz: '1) Profil va CV ni to‘ldiring.\n2) Agentliklar sizni ko‘radi; suhbat yoki to‘g‘ridan-to‘g‘ri ish taklifi kelishi mumkin.\n3) Taklifni qabul qilgach hujjat qadamlari ochiladi.\n4) Hujjatlar tugagach chipta yuboriladi — yangi karyerangiz boshlanadi.',
      tk: '1) Profil we CV dolduryň.\n2) Agentlikler sizi görýär; söhbet ýa-da göni iş teklibi gelip biler.\n3) Teklip kabul edilensoň resminama ädimleri açylýar.\n4) Resminamalar gutaransoň uçar biletiňiz iberilýär — täze karýeraňyz başlaýar.',
      de: '1) Profil und Lebenslauf vervollständigen.\n2) Agenturen sehen Sie; Interview oder direktes Angebot möglich.\n3) Nach Annahme öffnen sich die Dokumentenschritte.\n4) Wenn die Dokumente fertig sind, erhalten Sie Ihr Flugticket und starten Ihre neue Karriere.',
      th: '1) กรอกโปรไฟล์และเรซูเม่ให้ครบ\n2) เอเจนซีเห็นคุณ อาจได้สัมภาษณ์หรือข้อเสนองานโดยตรง\n3) เมื่อยอมรับข้อเสนอ ขั้นตอนเอกสารจะเปิด\n4) เมื่อเอกสารครบ จะส่งตั๋วเครื่องบิน และเริ่มงานใหม่ของคุณ',
      fa: '۱) پروفایل و رزومه را کامل کنید.\n۲) آژانس‌ها شما را می‌بینند؛ ممکن است مصاحبه یا پیشنهاد مستقیم بیاید.\n۳) با پذیرش پیشنهاد، مراحل مدارک باز می‌شود.\n۴) پس از تکمیل مدارک، بلیط پرواز ارسال می‌شود و کار جدیدتان آغاز می‌شود.',
    },
  },
  {
    id: 'cv',
    q: {
      tr: 'CV ve fotoğraflar neden önemli?',
      en: 'Why do CV and photos matter?',
      ru: 'Почему важны резюме и фото?',
      kk: 'CV мен фотолар неге маңызды?',
      ky: 'CV жана сүрөттөр эмне үчүн маанилүү?',
      uz: 'CV va fotolar nima uchun muhim?',
      tk: 'CV we suratlar näme üçin möhüm?',
      de: 'Warum sind Lebenslauf und Fotos wichtig?',
      th: 'ทำไมเรซูเม่และรูปถึงสำคัญ?',
      fa: 'چرا رزومه و عکس مهم است؟',
    },
    a: {
      tr: 'İşverenler ve acenteler sizi CV’niz ve fotoğraflarınız üzerinden değerlendirir. Vesikalık, yakın çekim ve boydan fotoğraflar ile kısa tanıtım videosu, doğru eşleşmeyi hızlandırır.',
      en: 'Employers and agencies assess you from your CV and photos. Portrait, close-up and full-body photos plus a short intro video help matching go faster.',
      ru: 'Работодатели и агентства оценивают вас по резюме и фото. Портрет, крупный план, фото в полный рост и короткое видео ускоряют подбор.',
      kk: 'Жұмыс берушілер мен агенттіктер сізді CV және фотоларыңыз арқылы бағалайды. Құжаттық, жақыннан және бойдан фотолар мен қысқа таныстыру видеосы дұрыс сәйкестендіруді жылдамдатады.',
      ky: 'Иш берүүчүлөр жана агенттиктер сизди CV жана сүрөттөрүңүз боюнча баалайт. Документтик, жакындан жана толук бойдон сүрөттөр менен кыска тааныштыруу видеосу туура тандоону тездетет.',
      uz: 'Ish beruvchilar va agentliklar sizni CV va fotolaringiz orqali baholaydi. Hujjat, yaqindan va to‘liq gavda fotolari hamda qisqa tanishtiruv videosı to‘g‘ri moslashni tezlashtiradi.',
      tk: 'Iş berijiler we agentlikler sizi CV we suratlar bilen bahalýarlar. Resminama, ýakyndan we doly boý suratlar bilen gysga tanyşdyryş wideosy dogry saýlamagy çaltlaşdyrýar.',
      de: 'Arbeitgeber und Agenturen bewerten Sie über Lebenslauf und Fotos. Porträt, Nahaufnahme, Ganzkörperfoto und ein kurzes Video beschleunigen das Matching.',
      th: 'นายจ้างและเอเจนซีประเมินคุณจากเรซูเม่และรูป รูปติดบัตร ระยะใกล้ เต็มตัว และวิดีโอแนะนำสั้นๆ ช่วยจับคูได้เร็วขึ้น',
      fa: 'کارفرمایان و آژانس‌ها شما را از روی رزومه و عکس‌ها می‌سنجند. عکس پرسنلی، نمای نزدیک، تمام‌قد و ویدیوی کوتاه معرفی، تطبیق را سریع‌تر می‌کند.',
    },
  },
  {
    id: 'offer',
    q: {
      tr: 'İş teklifi gelince ne yapmalıyım?',
      en: 'What should I do when I get a job offer?',
      ru: 'Что делать при предложении о работе?',
      kk: 'Жұмыс ұсынысы келгенде не істеуім керек?',
      ky: 'Жумуш сунушу келгенде эмне кылышым керек?',
      uz: 'Ish taklifi kelganda nima qilishim kerak?',
      tk: 'Iş teklibi gelende näme etmeli?',
      de: 'Was tun bei einem Jobangebot?',
      th: 'เมื่อมีข้อเสนองานควรทำอย่างไร?',
      fa: 'با دریافت پیشنهاد شغلی چه کنم؟',
    },
    a: {
      tr: 'Ana sayfadaki teklif bildirimine dokunun. Kabul ederseniz belge yükleme adımları açılır. Reddederseniz havuzda kalır, başka fırsatlar için görünür olursunuz.',
      en: 'Tap the offer alert on the home screen. If you accept, document upload steps open. If you decline, you stay in the pool and remain visible for other opportunities.',
      ru: 'Нажмите уведомление о предложении на главном экране. При принятии откроются шаги загрузки документов. При отказе вы остаётесь в пуле.',
      kk: 'Басты беттегі ұсыныс хабарламасына басыңыз. Қабылдасаңыз құжат жүктеу қадамдары ашылады. Бас тартсаңыз пулда қаласыз — басқа мүмкіндіктерге көрінесіз.',
      ky: 'Баш экрандагы сунуш билдирүүсүнө басыңыз. Кабыл алсаңыз документ жүктөө кадамдары ачылат. Баш тартсаңыз пулда каласыз — башка мүмкүнчүлүктөргө көрүнөсүз.',
      uz: 'Bosh ekrandagi taklif bildirishnomasiga bosing. Qabul qilsangiz hujjat yuklash qadamlari ochiladi. Rad etsangiz pulda qolasiz — boshqa imkoniyatlar uchun ko‘rinasiz.',
      tk: 'Baş sahypadaky teklip habarnamasyna basyň. Kabul etseňiz resminama ýükleme ädimleri açylýar. Ret etseňiz howuzda galýarsyňyz — beýleki mümkinçilikler üçin görünýärsiňiz.',
      de: 'Tippen Sie auf den Angebots-Hinweis auf dem Startbildschirm. Bei Annahme öffnen sich die Dokumentenschritte. Bei Ablehnung bleiben Sie im Pool.',
      th: 'แตะการแจ้งข้อเสนอบนหน้าแรก หากยอมรับ ขั้นตอนอัปโหลดเอกสารจะเปิด หากปฏิเสธ คุณยังอยู่ในพูลและมองเห็นได้สำหรับโอกาสอื่น',
      fa: 'هشدار پیشنهاد در صفحه اصلی را بزنید. با پذیرش، مراحل بارگذاری مدارک باز می‌شود. با رد، در استخر می‌مانید و برای فرصت‌های دیگر دیده می‌شوید.',
    },
  },
  {
    id: 'interview',
    q: {
      tr: 'Mülakat nasıl yapılır?',
      en: 'How do interviews work?',
      ru: 'Как проходят собеседования?',
      kk: 'Сұхбат қалай өтеді?',
      ky: 'Маек кантип өтөт?',
      uz: 'Suhbat qanday o‘tkaziladi?',
      tk: 'Söhbet nähili geçirilýär?',
      de: 'Wie laufen Interviews ab?',
      th: 'สัมภาษณ์ทำอย่างไร?',
      fa: 'مصاحبه چگونه انجام می‌شود؟',
    },
    a: {
      tr: 'Acente size saat önerir; uygun olanı seçersiniz. Planlanan saatte ana sayfadaki geri sayım / “Görüşmeye Katıl” ile uygulamadan görüntülü mülakata girersiniz.',
      en: 'The agency proposes times; you pick one. At the scheduled time, use the countdown / “Join the call” on the home screen to enter the video interview in the app.',
      ru: 'Агентство предлагает время; вы выбираете. В назначенный час через обратный отсчёт / «Присоединиться» на главном экране входите в видеоинтервью.',
      kk: 'Агенттік уақыт ұсынады; ыңғайлысын таңдайсыз. Белгіленген сағатта басты беттегі санақ / «Қосылу» арқылы қолданбадан бейне сұхбатқа кіресіз.',
      ky: 'Агенттик убакыт сунуштайт; ылайыктуусун тандайсыз. Белгиленген саатта баш экрандагы эсеп / «Кошулуу» менен колдонмодон видео маекке киресиз.',
      uz: 'Agentlik vaqt taklif qiladi; mosini tanlaysiz. Belgilangan soatda bosh ekrandagi hisob / “Qo‘shilish” orqali ilovadan video suhbatga kirasz.',
      tk: 'Agentlik wagt teklip edýär; amatlysyny saýlaýarsyňyz. Bellenen sagatda baş sahypadaky sanaw / «Goşul» bilen programmadan wideo söhbede girýärsiňiz.',
      de: 'Die Agentur schlägt Zeiten vor; Sie wählen eine. Zur Terminzeit treten Sie über Countdown / „Beitreten“ auf dem Startbildschirm dem Video-Interview bei.',
      th: 'เอเจนซีเสนอเวลา คุณเลือกหนึ่งช่วง เมื่อถึงเวลา ใช้ตัวนับถอยหลัง / “เข้าร่วมการสนทนา” บนหน้าแรกเพื่อเข้าสัมภาษณ์วิดีโอในแอป',
      fa: 'آژانس زمان پیشنهاد می‌دهد؛ یکی را انتخاب می‌کنید. در ساعت مقرر با شمارش معکوس / «پیوستن به تماس» در صفحه اصلی وارد مصاحبه ویدیویی در اپ می‌شوید.',
    },
  },
  {
    id: 'docs',
    q: {
      tr: 'Hangi belgeler istenir?',
      en: 'Which documents are required?',
      ru: 'Какие документы нужны?',
      kk: 'Қандай құжаттар қажет?',
      ky: 'Кайсы документтер керек?',
      uz: 'Qaysi hujjatlar kerak?',
      tk: 'Haýsy resminamalar gerek?',
      de: 'Welche Dokumente werden benötigt?',
      th: 'ต้องใช้เอกสารอะไรบ้าง?',
      fa: 'چه مدارکی لازم است؟',
    },
    a: {
      tr: 'Tipik sıra: pasaport, diploma, adli sicil, sağlık raporu; ardından sözleşme; sonra konsolosluk referansı ve çalışma vizesi. Acente uçak biletini son adımda yükler. Belgeler güvenli saklanır ve açık rızanızla paylaşılır.',
      en: 'Typical order: passport, diploma, criminal record, health report; then the contract; then consulate reference and work visa. The agency uploads the flight ticket in the last step. Documents are stored securely and shared only with your consent.',
      ru: 'Обычно: паспорт, диплом, справка о судимости, медсправка; затем договор; затем консульская справка и рабочая виза. Билет загружает агентство. Документы хранятся безопасно и передаются с вашего согласия.',
      kk: 'Әдеттегі тәртіп: төлқұжат, диплом, соттылық туралы анықтама, денсаулық анықтамасы; содан кейін шарт; кейін консулдық анықтама және жұмыс визасы. Агенттік ұшақ билетін соңғы қадамда жүктейді. Құжаттар қауіпсіз сақталады және сіздің келісіміңізбен ғана бөлісіледі.',
      ky: 'Кадимки тартип: паспорт, диплом, соттуулук справкасы, ден соолук справкасы; андан кийин келишим; кийин консулдук справка жана жумуш визасы. Агенттик учак билетин акыркы кадамда жүктөйт. Документтер коопсуз сакталат жана сиздин макулдугуңуз менен гана бөлүшүлөт.',
      uz: 'Odatiy tartib: pasport, diplom, sudlanganlik ma’lumotnomasi, sog‘liq haqidagi ma’lumotnoma; keyin shartnoma; so‘ng konsullik ma’lumotnomasi va ish vizasi. Agentlik chiptani oxirgi qadamda yuklaydi. Hujjatlar xavfsiz saqlanadi va faqat roziligingiz bilan ulashiladi.',
      tk: 'Adaty tertip: passport, diplom, jenaýat ýazgysy, saglyk şahadatnamasy; soň şertnama; soň konsullyk şahadatnamasy we iş wizasy. Agentlik uçar biletini soňky ädimde ýükleýär. Resminamalar howpsuz saklanýar we diňe razylygyňyz bilen paýlaşylýar.',
      de: 'Typisch: Pass, Diplom, Führungszeugnis, Gesundheitsbericht; dann Vertrag; dann Konsulatsreferenz und Arbeitsvisum. Das Flugticket lädt die Agentur. Dokumente sind sicher und werden nur mit Ihrer Einwilligung geteilt.',
      th: 'ลำดับทั่วไป: หนังสือเดินทาง ปริญญา ประวัติอาชญากรรม ใบรับรองสุขภาพ จากนั้นสัญญา แล้วอ้างอิงสถานกงสุลและวีซ่าทำงาน เอเจนซีอัปโหลดตั๋วเครื่องบินในขั้นตอนสุดท้าย เอกสารเก็บอย่างปลอดภัยและแชร์เฉพาะเมื่อคุณยินยอม',
      fa: 'ترتیب معمول: گذرنامه، مدرک تحصیلی، سوءپیشینه، گواهی سلامت؛ سپس قرارداد؛ بعد مرجع کنسولی و ویزای کار. آژانس بلیط را در گام آخر بارگذاری می‌کند. مدارک امن نگهداری و فقط با رضایت شما اشتراک می‌شود.',
    },
  },
  {
    id: 'contract',
    q: {
      tr: 'Sözleşme ve ödeme nasıl işler?',
      en: 'How do the contract and payment work?',
      ru: 'Как работают договор и оплата?',
      kk: 'Шарт пен төлем қалай жұмыс істейді?',
      ky: 'Келишим жана төлөм кантип иштейт?',
      uz: 'Shartnoma va to‘lov qanday ishlaydi?',
      tk: 'Şertnama we töleg nähili işleýär?',
      de: 'Wie funktionieren Vertrag und Zahlung?',
      th: 'สัญญาและการชำระเงินทำงานอย่างไร?',
      fa: 'قرارداد و پرداخت چگونه کار می‌کند؟',
    },
    a: {
      tr: 'Sözleşmeniz gönderildiğinde, hizmet bedeli ödemenizi yaparak sürece başlarsınız.',
      en: 'When your contract is sent, you start the process by paying the service fee.',
      ru: 'Когда договор отправлен, вы начинаете процесс, оплатив сервисный сбор.',
      kk: 'Шартыңыз жіберілгенде қызмет ақысын төлеп үдерісті бастайсыз.',
      ky: 'Келишимиңиз жөнөтүлгөндө кызмат акысын төлөп процессти баштайсыз.',
      uz: 'Shartnomangiz yuborilganda xizmat haqini to‘lab jarayonni boshlaysiz.',
      tk: 'Şertnamaňyz iberilende hyzmat tölegini töläp prosesi başlaýarsyňyz.',
      de: 'Sobald Ihr Vertrag gesendet wurde, starten Sie den Prozess mit der Servicegebühr.',
      th: 'เมื่อสัญญาถูกส่ง คุณเริ่มกระบวนการด้วยการชำระค่าบริการ',
      fa: 'وقتی قرارداد ارسال شد، با پرداخت هزینه خدمات فرایند را آغاز می‌کنید.',
    },
  },
  {
    id: 'pickup',
    q: {
      tr: 'Havaalanından otelime nasıl ulaşacağım?',
      en: 'How do I get from the airport to my hotel?',
      ru: 'Как добраться из аэропорта до отеля?',
      kk: 'Әуежайдан қонақүйге қалай жетемін?',
      ky: 'Аэропорттон мейманканага кантип жетем?',
      uz: 'Aeroportdan mehmonxonaga qanday boraman?',
      tk: 'Howa menzilinden myhmanhana nähili bararyn?',
      de: 'Wie komme ich vom Flughafen zum Hotel?',
      th: 'จากสนามบินไปโรงแรมอย่างไร?',
      fa: 'از فرودگاه تا هتل چگونه بروم؟',
    },
    a: {
      tr: 'Uçak biletiniz geldikten sonra sizi karşılayacak kişinin adı ve WhatsApp numarası uygulamada görünür. İndiğinizde bu numarayla iletişime geçersiniz; otelinize götürülürsünüz.',
      en: 'After your flight ticket arrives, the name and WhatsApp number of the person meeting you appear in the app. Contact them when you land; they take you to your hotel.',
      ru: 'После получения авиабилета в приложении появятся имя и WhatsApp встречающего. Свяжитесь после посадки — вас отвезут в отель.',
      kk: 'Ұшақ билетіңіз келгеннен кейін сізді қарсы алатын адамның аты мен WhatsApp нөмірі қолданбада көрінеді. Қонғанда осы нөмірге хабарласыңыз — сізді қонақүйге апарады.',
      ky: 'Учак билетиңиз келгенден кийин сизди тосуп алуучунун аты жана WhatsApp номери колдонмодо көрүнөт. Конуп түшкөндө ушул номерге байланышыңыз — сизди мейманканага алып барышат.',
      uz: 'Chiptangiz kelgach, sizni kutib oladigan shaxsning ismi va WhatsApp raqami ilovada ko‘rinadi. Qo‘nganingizda shu raqam bilan bog‘laning — sizni mehmonxonaga olib borishadi.',
      tk: 'Uçar biletiňiz gelensoň sizi garşylaýan adamyň ady we WhatsApp belgisі programmada görünýär. Inensoň şu belgi bilen habarlaşyň — sizi myhmanhana äkidýärler.',
      de: 'Nach dem Flugticket erscheinen in der App Name und WhatsApp der abholenden Person. Kontaktieren Sie sie nach der Landung; Sie werden zum Hotel gebracht.',
      th: 'หลังจากได้ตั๋วเครื่องบิน ชื่อและหมายเลข WhatsApp ของผู้มารับจะปรากฏในแอป ติดต่อเมื่อลงจอด แล้วจะพาไปโรงแรม',
      fa: 'پس از رسیدن بلیط، نام و شماره واتساپ شخص استقبال‌کننده در اپ ظاهر می‌شود. پس از فرود با او تماس بگیرید؛ شما را به هتل می‌رسانند.',
    },
  },
  {
    id: 'lang',
    q: {
      tr: 'Uygulamayı kendi dilimde kullanabilir miyim?',
      en: 'Can I use the app in my language?',
      ru: 'Можно ли пользоваться приложением на своём языке?',
      kk: 'Қолданбаны өз тілімде пайдалана аламын ба?',
      ky: 'Колдонмону өз тилимде колдоно аламбы?',
      uz: 'Ilovani o‘z tilimda ishlatishim mumkinmi?',
      tk: 'Programmany öz dilimde ulanyp bilýärinmi?',
      de: 'Kann ich die App in meiner Sprache nutzen?',
      th: 'ใช้แอปด้วยภาษาของฉันได้ไหม?',
      fa: 'می‌توانم اپ را به زبان خودم استفاده کنم؟',
    },
    a: {
      tr: 'Evet. Sağ üstteki menüden dil seçebilirsiniz. Süreç mesajları da karşı tarafın diline otomatik çevrilir.',
      en: 'Yes. Choose your language from the top-right menu. Process messages are also auto-translated for the other party.',
      ru: 'Да. Выберите язык в меню справа сверху. Сообщения процесса также переводятся автоматически.',
      kk: 'Иә. Жоғарғы оң мәзірден тіл таңдаңыз. Үдеріс хабарлары да қарсы тараптың тіліне автомат аударылады.',
      ky: 'Ооба. Жогорку оң менюдан тилди тандаңыз. Процесс билдирүүлөрү да карама-каршы тараптын тилине автомат которулат.',
      uz: 'Ha. Yuqori o‘ng menyudan tilni tanlang. Jarayon xabarlari ham boshqa tomon tiliga avtomatik tarjima qilinadi.',
      tk: 'Hawa. Ýokarky sag menýudan dili saýlaň. Proses habarlary hem garşy tarapyň diline awtomat terjime edilýär.',
      de: 'Ja. Wählen Sie die Sprache im Menü oben rechts. Prozess-Nachrichten werden ebenfalls automatisch übersetzt.',
      th: 'ได้ เลือกภาษาจากเมนูมุมขวาบน ข้อความในกระบวนการก็แปลให้อีกฝ่ายอัตโนมัติ',
      fa: 'بله. زبان را از منوی بالا‑راست انتخاب کنید. پیام‌های فرایند هم برای طرف مقابل خودکار ترجمه می‌شود.',
    },
  },
];

function pick(map, lang) {
  if (!map) return '';
  return map[lang] || map.en || map.tr || Object.values(map)[0] || '';
}

export function getCandidateFaq(lang) {
  const code = String(lang || 'tr').toLowerCase().slice(0, 2);
  return FAQ.map((item) => ({
    id: item.id,
    q: pick(item.q, code),
    a: pick(item.a, code),
  }));
}
